export { AccountSettingsPages } from "./accountSettingsPages"
export { CouponPages } from "./couponPages"
export { MyOrders } from "./myOrders"
export { MyComments } from "./myComments"
export { ShareWinPages } from "./shareWinPages"
export { NotificationsPages } from "./notificationsPages"
export { MyGaragePages } from "./myGaragePages"
export { MyFriendsPages } from "./myFriendsPages"